version: '3'
services:
  jupyter:
    build: 
      context: .
    volumes:
      - ./work:/work
    ports:
      - 8888:8888
    environment:
      - HF_HUB_TOKEN
    container_name: jupyter_notebook
    command: "jupyter notebook --ip 0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token="
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]